version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.0
  shellcheck: circleci/shellcheck@3.1

docker_auth: &docker_auth
  auth:
    username: $DOCKER_USERNAME
    password: $DOCKER_PASSWORD

resource_class: &resource_class
  resource_class: small

executors:
  default_small:
    docker:
      - image: circleci/circleci-cli:0.1.26646
        <<: *docker_auth
    <<: *resource_class
  python_small:
    docker:
      - image: cimg/python:3.11
        <<: *docker_auth
    <<: *resource_class

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          executor: python_small
          filters: *filters
      - orb-tools/pack:
          executor: default_small
          filters: *filters
      - orb-tools/review:
          executor: python_small
          filters: *filters
      - shellcheck/check:
          filters: *filters
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          executor: default_small
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          orb_name: circleci-templates
          requires: [orb-tools/lint, orb-tools/pack, orb-tools/review, shellcheck/check]
          filters: *filters
