version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.0

resource_class: &resource_class
  resource_class: small

default-executor: &default-executor
  name: orb-tools/default
  <<: *resource_class

python-executor: &python-executor
  name: orb-tools/python
  <<: *resource_class

filters: &filters
  tags:
    only: /.*/

release-filters: &release-filters
  branches:
    only: master
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          executor: *python-executor
          filters: *filters
      - orb-tools/pack:
          executor: *default-executor
          filters: *filters
      - orb-tools/review:
          executor: *python-executor
          filters: *filters
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          executor: *default-executor
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          orb_name: circleci-templates
          requires: [orb-tools/lint, orb-tools/pack, orb-tools/review]
          filters: *release-filters
