version: 2.1
orbs:
  # Your orb will be automatically injected here during the pipeline.
  # Reference your orb's jobs and commands below as they will exist when built.
  orb-tools: circleci/orb-tools@12.0
  # The orb definition is intentionally not included here. It will be injected into the pipeline.
  circleci-templates: {}

resource_class: &resource_class
  resource_class: small

default-executor: &default-executor
  name: orb-tools/default
  <<: *resource_class

filters: &filters
  branches:
    only: master

# Filter for release tags.
release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

workflows:
  dev_release:
    jobs:
      - orb-tools/pack:
          name: dev_pack
          executor: *default-executor
          filters: *filters
      - orb-tools/publish:
          name: dev_publish
          executor: *default-executor
          orb_name: devatherock/circleci-templates
          vcs_type: << pipeline.project.type >>
          pub_type: dev
          dev_tags: "dev:alpha,dev:${CIRCLE_SHA1:0:8}"
          requires:
            - dev_pack
          context: orb-publishing
          filters: *filters

  release:
    jobs:
      # The orb must be re-packed for publishing, and saved to the workspace.
      - orb-tools/pack:
          executor: *default-executor
          filters: *release-filters
      - orb-tools/publish:
          executor: *default-executor
          orb_name: devatherock/circleci-templates
          vcs_type: << pipeline.project.type >>
          pub_type: production
          # Ensure this job requires all test jobs and the pack job.
          requires:
            - orb-tools/pack
          context: orb-publishing
          filters: *release-filters
